### ISSUE TITLE
Edge support

### ISSUE THREAD

**Issue by Bansikov** [webcast/webcaster#6]
Hello!

I checked this nice tool with MS Edge, 1 error need to be fixed in client.js at line:
      this.webcast = this.context.createWebcastSource(4096, this.defaultChannels);
change **this.defaultChannels** to **defaultChannels**.

Now its seem to be worked with Edge too, but only 5 second, after click **Start streaming**.
Then CPU increased to 100%  and memory over 1.5GB.
Why its happened, any idea?

**Comment by toots** [comment]
Thanks for the report! Should be fixed now..

High CPU usage is most likely due to audio compression. This is done via a Javascript build of libshine which requires the Javascript engine to be optimized for a subset of the language called ASMJS, which is close to actual machine code.

To test this, you can try to broadcast in wave format and see if you have the same CPU issues.

**Comment by Bansikov** [comment]
**EDITED:**
Ok, i have tested Edge on power PC - i7-7700 
RAW: cpu 10%, memory up to 1gb => "interrupted STREAMING" over liquidsoup
MP3: cpu 30% memory up to 1gb =>  "too slow STREAMING, no sound" over liquidsoup

Its enough CPU.
Maybe that is JS Worker problem?

```
 ref1.encode(audio, function(data) {
 console.dir(data);
```
I checked encoded DATA here, and the chunks received in Chrome are very fast.
In Edge 1-2 sec fast and then a little slower with RAW data, and very very very slow with mp3 encoder.

**Comment by Bansikov** [comment]
I have edited my comment above.

**Comment by toots** [comment]
Hi,

This is most likely linked to Edge's support of the [asm.js](https://en.wikipedia.org/wiki/Asm.js) technologies..
